Repository ACMAS/ACMAS-Frontend, pull requests merged in 2022-10, with the labels that each got.

#54 Fix server startup instructions for ACMAS-Frontend
  README.md
Labels: documentation

#53 VSCode configuration for debugging
  .vscode/launch.json
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted

#52 Adding a db save on manual question entry
  ACMAS/web/upload.py
Labels: bug, hacktoberfest-accepted

#60 Bootstrap and Navbar implementation
  .github/workflows/django.yml
  .github/workflows/super-linter.yml
  ACMAS/db.sqlite3
  ACMAS/web/static/css/bootstrap-grid.css
  ACMAS/web/static/css/bootstrap-grid.css.map
  ACMAS/web/static/css/bootstrap-grid.min.css
  ACMAS/web/static/css/bootstrap-grid.min.css.map
  ACMAS/web/static/css/bootstrap-reboot.css
  ACMAS/web/static/css/bootstrap-reboot.css.map
  ACMAS/web/static/css/bootstrap-reboot.min.css
  ACMAS/web/static/css/bootstrap-reboot.min.css.map
  ACMAS/web/static/css/bootstrap.css
  ACMAS/web/static/css/bootstrap.css.map
  ACMAS/web/static/css/bootstrap.min.css
  ACMAS/web/static/css/bootstrap.min.css.map
  ACMAS/web/static/img/logo.v1.svg
  ACMAS/web/static/img/logo.v2-unused.svg
  ACMAS/web/static/img/star.png
  ACMAS/web/static/img/star.svg
  ACMAS/web/static/index.html
  ACMAS/web/static/js/bootstrap.bundle.js
  ACMAS/web/static/js/bootstrap.bundle.js.map
  ACMAS/web/static/js/bootstrap.bundle.min.js
  ACMAS/web/static/js/bootstrap.bundle.min.js.map
  ACMAS/web/static/js/bootstrap.js
  ACMAS/web/static/js/bootstrap.js.map
  ACMAS/web/static/js/bootstrap.min.js
  ACMAS/web/static/js/bootstrap.min.js.map
  ACMAS/web/static/styles/commons.css
  ACMAS/web/static/styles/home-style.css
  ACMAS/web/static/styles/search-by-course-style.css
  ACMAS/web/static/styles/upload-options.css
  ACMAS/web/static/styles/upload-search-style.css
  ACMAS/web/templates/__init__.py
  ACMAS/web/templates/navbar.html
  ACMAS/web/templates/pdf-reader.html
  ACMAS/web/templates/search-by-course.html
  ACMAS/web/templates/search-by-question.html
  ACMAS/web/templates/search-results.html
  ACMAS/web/templates/upload-file.html
  ACMAS/web/templates/upload-manually.html
  ACMAS/web/templates/upload-options.html
  ACMAS/web/urls.py
  ACMAS/web/views.py
Labels: enhancement, hacktoberfest-accepted

#64 Removed old logos and fixed centering
  ACMAS/db.sqlite3
  ACMAS/web/static/styles/pdf-reader-style.css
  ACMAS/web/static/styles/search-by-course-style.css
  ACMAS/web/templates/pdf-reader.html
  ACMAS/web/templates/search-by-course.html
  ACMAS/web/templates/search-results.html
Labels: bug, hacktoberfest-accepted
